import type { GradeType, SubjectType } from "@notenrechner/shared";

export type DemoSubject = {
  id: string;
  name: string;
  shortName: string | null;
  color: string | null;
  subjectType: SubjectType;
  archived: boolean;
};

export type DemoTerm = {
  id: string;
  name: string;
  startDate: string | null;
  endDate: string | null;
  isActive: boolean;
};

export type DemoGrade = {
  id: string;
  subjectId: string;
  termId: string | null;
  title: string;
  value: number;
  weight: number;
  date: string | null;
  type: GradeType;
  notes: string | null;
};

export type DemoState = {
  subjects: DemoSubject[];
  terms: DemoTerm[];
  grades: DemoGrade[];
};

export const demoSeed: DemoState = {
  subjects: [
    {
      id: "ma",
      name: "Mathematik",
      shortName: "MA",
      color: "#1f7a68",
      subjectType: "bms_exam_subject",
      archived: false,
    },
    {
      id: "de",
      name: "Deutsch",
      shortName: "DE",
      color: "#2b6cb0",
      subjectType: "bms_exam_subject",
      archived: false,
    },
    {
      id: "en",
      name: "Englisch",
      shortName: "EN",
      color: "#805ad5",
      subjectType: "bms_exam_subject",
      archived: false,
    },
    {
      id: "wr",
      name: "Wirtschaft und Recht",
      shortName: "WR",
      color: "#d97706",
      subjectType: "bms_exam_subject",
      archived: false,
    },
    {
      id: "finance",
      name: "Finanz- und Rechnungswesen",
      shortName: "FRW",
      color: "#c05621",
      subjectType: "bms_non_exam_subject",
      archived: false,
    },
    {
      id: "history",
      name: "Geschichte und Politik",
      shortName: "GP",
      color: "#4a5568",
      subjectType: "bms_non_exam_subject",
      archived: false,
    },
    {
      id: "science",
      name: "Naturwissenschaften",
      shortName: "NW",
      color: "#2f855a",
      subjectType: "bms_non_exam_subject",
      archived: false,
    },
    {
      id: "technology",
      name: "Technik und Umwelt",
      shortName: "TU",
      color: "#319795",
      subjectType: "bms_non_exam_subject",
      archived: false,
    },
    {
      id: "idpa-idaf",
      name: "IDPA / IDAF",
      shortName: "IDPA",
      color: "#6b46c1",
      subjectType: "bms_idpa_idaf",
      archived: false,
    },
    {
      id: "efz-prog",
      name: "Applikationsentwicklung",
      shortName: "APP",
      color: "#2563eb",
      subjectType: "efz_school_module",
      archived: false,
    },
    {
      id: "efz-db",
      name: "Datenbanken",
      shortName: "DB",
      color: "#0f766e",
      subjectType: "efz_school_module",
      archived: false,
    },
    {
      id: "efz-uek",
      name: "UeK Module",
      shortName: "UeK",
      color: "#7c2d12",
      subjectType: "efz_uek_module",
      archived: false,
    },
    {
      id: "ipa",
      name: "IPA",
      shortName: "IPA",
      color: "#be123c",
      subjectType: "custom",
      archived: false,
    },
  ],
  terms: [
    {
      id: "sem-3",
      name: "3. Semester",
      startDate: "2026-02-01",
      endDate: "2026-07-10",
      isActive: true,
    },
    {
      id: "sem-2",
      name: "2. Semester",
      startDate: "2025-08-18",
      endDate: "2026-01-23",
      isActive: false,
    },
  ],
  grades: [
    {
      id: "ma-sem-2",
      subjectId: "ma",
      termId: "sem-2",
      title: "Algebra Semesterprobe",
      value: 4.5,
      weight: 1,
      date: "2025-11-21",
      type: "exam",
      notes: "Zaehlt als BMS Zeugnisnote fuer Mathematik.",
    },
    {
      id: "ma-sem-3",
      subjectId: "ma",
      termId: "sem-3",
      title: "Funktionen",
      value: 5,
      weight: 1,
      date: "2026-03-12",
      type: "exam",
      notes: null,
    },
    {
      id: "ma-written",
      subjectId: "ma",
      termId: null,
      title: "Schriftliche Abschlusspruefung",
      value: 4.5,
      weight: 1,
      date: "2026-06-03",
      type: "written",
      notes: null,
    },
    {
      id: "ma-oral",
      subjectId: "ma",
      termId: null,
      title: "Muendliche Abschlusspruefung",
      value: 5,
      weight: 1,
      date: "2026-06-17",
      type: "oral",
      notes: null,
    },
    {
      id: "de-sem-2",
      subjectId: "de",
      termId: "sem-2",
      title: "Literaturarbeit",
      value: 4,
      weight: 1,
      date: "2025-10-29",
      type: "project",
      notes: null,
    },
    {
      id: "de-sem-3",
      subjectId: "de",
      termId: "sem-3",
      title: "Essay",
      value: 4.5,
      weight: 1,
      date: "2026-03-18",
      type: "project",
      notes: "Argumentation war solide, Sprache noch schaerfen.",
    },
    {
      id: "de-written",
      subjectId: "de",
      termId: null,
      title: "Schriftliche Abschlusspruefung",
      value: 4.5,
      weight: 1,
      date: "2026-06-04",
      type: "written",
      notes: null,
    },
    {
      id: "de-oral",
      subjectId: "de",
      termId: null,
      title: "Muendliche Abschlusspruefung",
      value: 4,
      weight: 1,
      date: "2026-06-18",
      type: "oral",
      notes: null,
    },
    {
      id: "en-sem-2",
      subjectId: "en",
      termId: "sem-2",
      title: "Listening und Reading",
      value: 5,
      weight: 1,
      date: "2025-12-05",
      type: "exam",
      notes: null,
    },
    {
      id: "en-sem-3",
      subjectId: "en",
      termId: "sem-3",
      title: "Presentation",
      value: 4.5,
      weight: 1,
      date: "2026-03-28",
      type: "project",
      notes: "Semesterleistung, keine Abschlusspruefung.",
    },
    {
      id: "en-written",
      subjectId: "en",
      termId: null,
      title: "Schriftliche Abschlusspruefung",
      value: 4.5,
      weight: 1,
      date: "2026-06-05",
      type: "written",
      notes: null,
    },
    {
      id: "en-oral",
      subjectId: "en",
      termId: null,
      title: "Muendliche Abschlusspruefung",
      value: 4.5,
      weight: 1,
      date: "2026-06-19",
      type: "oral",
      notes: null,
    },
    {
      id: "wr-sem-2",
      subjectId: "wr",
      termId: "sem-2",
      title: "Fallstudie",
      value: 3.75,
      weight: 1,
      date: "2025-11-12",
      type: "project",
      notes: null,
    },
    {
      id: "wr-sem-3",
      subjectId: "wr",
      termId: "sem-3",
      title: "Vertragsrecht Test",
      value: 4.25,
      weight: 1,
      date: "2026-04-02",
      type: "exam",
      notes: null,
    },
    {
      id: "wr-written",
      subjectId: "wr",
      termId: null,
      title: "Schriftliche Abschlusspruefung",
      value: 4,
      weight: 1,
      date: "2026-06-08",
      type: "written",
      notes: null,
    },
    {
      id: "wr-oral",
      subjectId: "wr",
      termId: null,
      title: "Muendliche Abschlusspruefung",
      value: 4,
      weight: 1,
      date: "2026-06-20",
      type: "oral",
      notes: null,
    },
    {
      id: "finance-sem-2",
      subjectId: "finance",
      termId: "sem-2",
      title: "Bilanz und Erfolgsrechnung",
      value: 4,
      weight: 1,
      date: "2025-12-12",
      type: "exam",
      notes: null,
    },
    {
      id: "finance-sem-3",
      subjectId: "finance",
      termId: "sem-3",
      title: "Kalkulation",
      value: 4.5,
      weight: 1,
      date: "2026-04-17",
      type: "exam",
      notes: null,
    },
    {
      id: "history-sem-2",
      subjectId: "history",
      termId: "sem-2",
      title: "Politische Systeme",
      value: 4.5,
      weight: 1,
      date: "2025-09-30",
      type: "exam",
      notes: null,
    },
    {
      id: "history-sem-3",
      subjectId: "history",
      termId: "sem-3",
      title: "Zeitgeschichte Vortrag",
      value: 4.5,
      weight: 1,
      date: "2026-02-27",
      type: "oral",
      notes: null,
    },
    {
      id: "science-sem-2",
      subjectId: "science",
      termId: "sem-2",
      title: "Laborjournal",
      value: 4.5,
      weight: 1,
      date: "2025-12-18",
      type: "project",
      notes: null,
    },
    {
      id: "science-sem-3",
      subjectId: "science",
      termId: "sem-3",
      title: "Oekologie Test",
      value: 4.25,
      weight: 1,
      date: "2026-05-08",
      type: "exam",
      notes: null,
    },
    {
      id: "technology-sem-2",
      subjectId: "technology",
      termId: "sem-2",
      title: "Energieprojekt",
      value: 4,
      weight: 1,
      date: "2025-10-17",
      type: "project",
      notes: null,
    },
    {
      id: "technology-sem-3",
      subjectId: "technology",
      termId: "sem-3",
      title: "Umwelttechnik Test",
      value: 4.25,
      weight: 1,
      date: "2026-05-01",
      type: "exam",
      notes: null,
    },
    {
      id: "idpa-final",
      subjectId: "idpa-idaf",
      termId: "sem-3",
      title: "IDPA Schlussnote",
      value: 5,
      weight: 1,
      date: "2026-05-22",
      type: "project",
      notes: null,
    },
    {
      id: "idaf-1",
      subjectId: "idpa-idaf",
      termId: "sem-2",
      title: "IDAF Modul 1",
      value: 4.5,
      weight: 1,
      date: "2025-12-08",
      type: "module",
      notes: null,
    },
    {
      id: "idaf-2",
      subjectId: "idpa-idaf",
      termId: "sem-3",
      title: "IDAF Modul 2",
      value: 5,
      weight: 1,
      date: "2026-03-06",
      type: "module",
      notes: null,
    },
    {
      id: "efz-prog-1",
      subjectId: "efz-prog",
      termId: "sem-3",
      title: "Modul 294 Frontend",
      value: 4.5,
      weight: 1,
      date: "2026-02-20",
      type: "module",
      notes: null,
    },
    {
      id: "efz-prog-2",
      subjectId: "efz-prog",
      termId: "sem-3",
      title: "Modul 295 Backend",
      value: 5,
      weight: 1,
      date: "2026-04-24",
      type: "module",
      notes: null,
    },
    {
      id: "efz-db-1",
      subjectId: "efz-db",
      termId: "sem-2",
      title: "Modul 164 Datenbanken",
      value: 4,
      weight: 1,
      date: "2025-11-28",
      type: "module",
      notes: null,
    },
    {
      id: "efz-db-2",
      subjectId: "efz-db",
      termId: "sem-3",
      title: "Modul 141 Datenmodellierung",
      value: 4.5,
      weight: 1,
      date: "2026-05-15",
      type: "module",
      notes: null,
    },
    {
      id: "efz-uek-1",
      subjectId: "efz-uek",
      termId: "sem-2",
      title: "UeK Cloud Services",
      value: 5,
      weight: 1,
      date: "2025-09-26",
      type: "module",
      notes: null,
    },
    {
      id: "efz-uek-2",
      subjectId: "efz-uek",
      termId: "sem-3",
      title: "UeK Security",
      value: 5.5,
      weight: 1,
      date: "2026-03-20",
      type: "module",
      notes: null,
    },
    {
      id: "ipa-grade",
      subjectId: "ipa",
      termId: "sem-3",
      title: "IPA Facharbeit",
      value: 4.5,
      weight: 1,
      date: "2026-06-12",
      type: "project",
      notes: null,
    },
  ],
};
